/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface UpdateNotificationPreference$Params {
  userId: number;
  type: string;
  enabled: boolean;
}

export function updateNotificationPreference(http: HttpClient, rootUrl: string, params: UpdateNotificationPreference$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, updateNotificationPreference.PATH, 'put');
  if (params) {
    rb.path('userId', params.userId, {});
    rb.query('type', params.type, {});
    rb.query('enabled', params.enabled, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

updateNotificationPreference.PATH = '/api/settings/{userId}/notifications';
