/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { IncomeDto } from '../../models/income-dto';

export interface IncomeControllerRemove$Params {
  id: number;
}

export function incomeControllerRemove(http: HttpClient, rootUrl: string, params: IncomeControllerRemove$Params, context?: HttpContext): Observable<StrictHttpResponse<IncomeDto>> {
  const rb = new RequestBuilder(rootUrl, incomeControllerRemove.PATH, 'delete');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<IncomeDto>;
    })
  );
}

incomeControllerRemove.PATH = '/v1/incomes/{id}';
