/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { IncomeDto } from '../../models/income-dto';
import { IncomeDtoCreateUpdate } from '../../models/income-dto-create-update';

export interface IncomeControllerUpdate$Params {
  id: number;
      body: IncomeDtoCreateUpdate
}

export function incomeControllerUpdate(http: HttpClient, rootUrl: string, params: IncomeControllerUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<IncomeDto>> {
  const rb = new RequestBuilder(rootUrl, incomeControllerUpdate.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<IncomeDto>;
    })
  );
}

incomeControllerUpdate.PATH = '/v1/incomes/{id}';
