/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { IncomeListDto } from '../../models/income-list-dto';
import { SearchFieldValue } from '../../models/search-field-value';

<<<<<<<< HEAD:src/app/api/fn/income-controller/income-controller-get-by-user-id.ts
export interface IncomeControllerGetByUserId$Params {

/**
 * Id do usuario
 */
  id: number;
}

export function incomeControllerGetByUserId(http: HttpClient, rootUrl: string, params: IncomeControllerGetByUserId$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<IncomeListDto>>> {
  const rb = new RequestBuilder(rootUrl, incomeControllerGetByUserId.PATH, 'get');
========
export interface IncomeControllerSearchFieldsAction$Params {
      body: Array<SearchFieldValue>
}

export function incomeControllerSearchFieldsAction(http: HttpClient, rootUrl: string, params: IncomeControllerSearchFieldsAction$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<IncomeListDto>>> {
  const rb = new RequestBuilder(rootUrl, incomeControllerSearchFieldsAction.PATH, 'post');
>>>>>>>> branch-jonathan-final:src/app/api/fn/income-controller/income-controller-search-fields-action.ts
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<IncomeListDto>>;
    })
  );
}

<<<<<<<< HEAD:src/app/api/fn/income-controller/income-controller-get-by-user-id.ts
incomeControllerGetByUserId.PATH = '/v1/incomes/user/{id}';
========
incomeControllerSearchFieldsAction.PATH = '/v1/incomes/search-fields';
>>>>>>>> branch-jonathan-final:src/app/api/fn/income-controller/income-controller-search-fields-action.ts
