/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


import {GenericDto} from "../../api/models/generic-dto";
import {PageableObject} from "../../api/models/pageable-object";
import {SortObject} from "../../api/models/sort-object";

export interface PageDto<MODEL extends GenericDto> {
  content?: Array<MODEL>;
  empty?: boolean;
  first?: boolean;
  last?: boolean;
  number?: number;
  numberOfElements?: number;
  pageable?: PageableObject;
  size?: number;
  sort?: SortObject;
  totalElements?: number;
  totalPages?: number;
}
