/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Pageable } from '../../models/pageable';
import { PageGoalListDto } from '../../models/page-goal-list-dto';

export interface GoalControllerListAllPage$Params {
  page: Pageable;
}

export function goalControllerListAllPage(http: HttpClient, rootUrl: string, params: GoalControllerListAllPage$Params, context?: HttpContext): Observable<StrictHttpResponse<PageGoalListDto>> {
  const rb = new RequestBuilder(rootUrl, goalControllerListAllPage.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageGoalListDto>;
    })
  );
}

goalControllerListAllPage.PATH = '/v1/goals/page';
