/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GoalDto } from '../../models/goal-dto';
import { GoalDtoCreate } from '../../models/goal-dto-create';

export interface GoalControllerCreate$Params {
      body: GoalDtoCreate
}

export function goalControllerCreate(http: HttpClient, rootUrl: string, params: GoalControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<GoalDto>> {
  const rb = new RequestBuilder(rootUrl, goalControllerCreate.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GoalDto>;
    })
  );
}

goalControllerCreate.PATH = '/v1/goals';
