/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Pageable } from '../../models/pageable';
import { PageExpenseListDto } from '../../models/page-expense-list-dto';

export interface ExpenseControllerListAllPage$Params {
  page: Pageable;
}

export function expenseControllerListAllPage(http: HttpClient, rootUrl: string, params: ExpenseControllerListAllPage$Params, context?: HttpContext): Observable<StrictHttpResponse<PageExpenseListDto>> {
  const rb = new RequestBuilder(rootUrl, expenseControllerListAllPage.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageExpenseListDto>;
    })
  );
}

expenseControllerListAllPage.PATH = '/1.0/expenses/page';
