/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Pageable } from '../../models/pageable';
import { PageExpenseListDto } from '../../models/page-expense-list-dto';

export interface ExpenseControllerListAllPageByUser$Params {
  page: Pageable;

/**
 * Id do usuario
 */
  id: number;
}

export function expenseControllerListAllPageByUser(http: HttpClient, rootUrl: string, params: ExpenseControllerListAllPageByUser$Params, context?: HttpContext): Observable<StrictHttpResponse<PageExpenseListDto>> {
  const rb = new RequestBuilder(rootUrl, expenseControllerListAllPageByUser.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageExpenseListDto>;
    })
  );
}

expenseControllerListAllPageByUser.PATH = '/v1/expenses/page/user/{id}';
