/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ExpenseDto } from '../../models/expense-dto';

export interface ExpenseControllerGetById$Params {

/**
 * Id da entidade
 */
  id: number;
}

export function expenseControllerGetById(http: HttpClient, rootUrl: string, params: ExpenseControllerGetById$Params, context?: HttpContext): Observable<StrictHttpResponse<ExpenseDto>> {
  const rb = new RequestBuilder(rootUrl, expenseControllerGetById.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ExpenseDto>;
    })
  );
}

expenseControllerGetById.PATH = '/v1/expenses/{id}';
