/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ExpenseDto } from '../../models/expense-dto';
import { ExpenseDtoCreateUpdate } from '../../models/expense-dto-create-update';

export interface ExpenseControllerUpdate$Params {
  id: number;
      body: ExpenseDtoCreateUpdate
}

export function expenseControllerUpdate(http: HttpClient, rootUrl: string, params: ExpenseControllerUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<ExpenseDto>> {
  const rb = new RequestBuilder(rootUrl, expenseControllerUpdate.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ExpenseDto>;
    })
  );
}

expenseControllerUpdate.PATH = '/v1/expenses/{id}';
