/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { NotificationPreferenceDto } from '../../models/notification-preference-dto';
import { NotificationPreferenceDtoCreateUpdate } from '../../models/notification-preference-dto-create-update';

export interface NotificationPreferenceControllerCreate$Params {
      body: NotificationPreferenceDtoCreateUpdate
}

export function notificationPreferenceControllerCreate(http: HttpClient, rootUrl: string, params: NotificationPreferenceControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<NotificationPreferenceDto>> {
  const rb = new RequestBuilder(rootUrl, notificationPreferenceControllerCreate.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<NotificationPreferenceDto>;
    })
  );
}

notificationPreferenceControllerCreate.PATH = '/v1/notification-preferences';
