/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Pageable } from '../../models/pageable';
import { PageNotificationPreferenceDto } from '../../models/page-notification-preference-dto';

export interface NotificationPreferenceControllerListAllPage$Params {
  page: Pageable;
}

export function notificationPreferenceControllerListAllPage(http: HttpClient, rootUrl: string, params: NotificationPreferenceControllerListAllPage$Params, context?: HttpContext): Observable<StrictHttpResponse<PageNotificationPreferenceDto>> {
  const rb = new RequestBuilder(rootUrl, notificationPreferenceControllerListAllPage.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageNotificationPreferenceDto>;
    })
  );
}

notificationPreferenceControllerListAllPage.PATH = '/1.0/notification-preferences/page';
