/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { NotificationPreferenceDto } from '../../models/notification-preference-dto';

export interface NotificationPreferenceControllerRemove$Params {
  id: number;
}

export function notificationPreferenceControllerRemove(http: HttpClient, rootUrl: string, params: NotificationPreferenceControllerRemove$Params, context?: HttpContext): Observable<StrictHttpResponse<NotificationPreferenceDto>> {
  const rb = new RequestBuilder(rootUrl, notificationPreferenceControllerRemove.PATH, 'delete');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<NotificationPreferenceDto>;
    })
  );
}

notificationPreferenceControllerRemove.PATH = '/v1/notification-preferences/{id}';
