/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { IncomeControllerService } from './services/income-controller.service';
export { CategoryControllerService } from './services/category-controller.service';
export { TestControllerService } from './services/test-controller.service';
