/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Informações de Autenticação
 */
export interface AuthDto {

  /**
   * Login do Usuário
   */
  login: string;

  /**
   * Senha do Usuário
   */
  password: string;
}
