/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Informações da Redefinição de Senha
 */
export interface AuthUserDto {

  /**
   * Confirmar Senha
   */
  confirmPassword?: string;

  /**
   * E-mail do Usuário onde a solicitação de senha foi enviada. (Campo não será considerado como parâmetro de entrada)
   */
  email?: string;

  /**
   * Nova Senha
   */
  newPassword?: string;

  /**
   * Senha Antiga
   */
  oldPassword?: string;
}
