/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { User } from '../models/user';
export interface Category {
  id?: number;
  iexpense?: boolean;
  name?: string;
  user?: User;
}
