/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Category } from '../models/category';
export interface ExpenseListDto {
  amount?: number;
  category?: Category;
  description?: string;
  expenseDate?: string;
  id?: number;
  leadTime?: number;
  name?: string;
  repeatable?: 'WEEKLY' | 'MONTHLY' | 'YEARLY' | 'DONT_REPEATS';
}
