/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ExpenseDto {
  amount?: number;
  categoryName?: string;
  description?: string;
  id?: number;
  incomeDate?: string;
  leadTime?: number;
  name?: string;
}
