/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Atributos de validação
 */
export interface FieldResponse {

  /**
   * Nome do atributo
   */
  attribute?: string;

  /**
   * Descrição da validação
   */
  description?: string;
}
