/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface GoalDtoCreate {
  amountTotal?: number;
  goalDate?: string;
  name?: string;
  userId?: number;
}
