/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface GoalDto {
  amountReached?: number;
  amountTotal?: number;
  goalDate?: string;
  id?: number;
  name?: string;
  userId?: number;
}
