/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Category } from '../models/category';
export interface IncomeListDto {
  amount?: number;
  category?: Category;
  description?: string;
  id?: number;
  incomeDate?: string;
  leadTime?: number;
  name?: string;
  repeat?: boolean;
}
