/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface IncomeDtoCreateUpdate {
  amount?: number;
  categoryName?: string;
  description?: string;
  incomeDate?: string;
  leadTime?: number;
  name?: string;
  repeat?: boolean;
}
