/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FieldResponse } from '../models/field-response';
export interface MessageResponse {

  /**
   * Atributos de validação
   */
  attributes?: Array<FieldResponse>;

  /**
   * Código da Mensagem
   */
  code?: string;

  /**
   * Descrição erro HTTP
   */
  error?: string;

  /**
   * Mensagem de negócio
   */
  message?: string;

  /**
   * Parâmetros da mensagem
   */
  parameters?: Array<{
}>;

  /**
   * Status HTTP
   */
  status?: number;
}
