/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface NotificationDto {
  createdAt?: string;
  id?: number;
  message?: string;
  type?: string;
  userId?: number;
}
