/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface NotificationPreferenceDtoCreateUpdate {
  enabled?: boolean;
  type?: string;
  userId?: number;
}
