/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface NotificationPreferenceDto {
  enabled?: boolean;
  id?: number;
  type?: string;
  userId?: number;
}
