/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Informações de Criação
 */
export interface UserCreateDto {
  email?: string;
  login?: string;
  password?: string;
}
