/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Login } from '../models/login';
export interface User {
  activeState?: boolean;
  email?: string;
  id?: number;
  login?: string;
  loginEnt?: Login;
  roles?: Array<string>;
}
