/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { CredencialDto } from '../models/credencial-dto';
import { getInfoByToken } from '../fn/auth-api/get-info-by-token';
import { GetInfoByToken$Params } from '../fn/auth-api/get-info-by-token';
import { getInfoByTokenValidacao } from '../fn/auth-api/get-info-by-token-validacao';
import { GetInfoByTokenValidacao$Params } from '../fn/auth-api/get-info-by-token-validacao';
import { login } from '../fn/auth-api/login';
import { Login$Params } from '../fn/auth-api/login';
import { recoverPassword } from '../fn/auth-api/recover-password';
import { RecoverPassword$Params } from '../fn/auth-api/recover-password';
import { refresh } from '../fn/auth-api/refresh';
import { Refresh$Params } from '../fn/auth-api/refresh';
import { resetPassword } from '../fn/auth-api/reset-password';
import { ResetPassword$Params } from '../fn/auth-api/reset-password';

@Injectable({ providedIn: 'root' })
export class AuthApiService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `resetPassword()` */
  static readonly ResetPasswordPath = '/api/v1/auth/reset-password';

  /**
   * Inclusão ou alteração a senha do usuário.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `resetPassword()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  resetPassword$Response(params: ResetPassword$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CredencialDto>>> {
    return resetPassword(this.http, this.rootUrl, params, context);
  }

  /**
   * Inclusão ou alteração a senha do usuário.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `resetPassword$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  resetPassword(params: ResetPassword$Params, context?: HttpContext): Observable<Array<CredencialDto>> {
    return this.resetPassword$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<CredencialDto>>): Array<CredencialDto> => r.body)
    );
  }

  /** Path part for operation `login()` */
  static readonly LoginPath = '/api/v1/auth/login';

  /**
   * Concede o token de acesso ao Usuário através do 'login' e 'senha'.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `login()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  login$Response(params: Login$Params, context?: HttpContext): Observable<StrictHttpResponse<CredencialDto>> {
    return login(this.http, this.rootUrl, params, context);
  }

  /**
   * Concede o token de acesso ao Usuário através do 'login' e 'senha'.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `login$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  login(params: Login$Params, context?: HttpContext): Observable<CredencialDto> {
    return this.login$Response(params, context).pipe(
      map((r: StrictHttpResponse<CredencialDto>): CredencialDto => r.body)
    );
  }

  /** Path part for operation `recoverPassword()` */
  static readonly RecoverPasswordPath = '/api/v1/auth/reset-password/request/{email}';

  /**
   * Realiza a solicitação de recuperar a senha do usuário.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `recoverPassword()` instead.
   *
   * This method doesn't expect any request body.
   */
  recoverPassword$Response(params: RecoverPassword$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CredencialDto>>> {
    return recoverPassword(this.http, this.rootUrl, params, context);
  }

  /**
   * Realiza a solicitação de recuperar a senha do usuário.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `recoverPassword$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  recoverPassword(params: RecoverPassword$Params, context?: HttpContext): Observable<Array<CredencialDto>> {
    return this.recoverPassword$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<CredencialDto>>): Array<CredencialDto> => r.body)
    );
  }

  /** Path part for operation `refresh()` */
  static readonly RefreshPath = '/api/v1/auth/refresh';

  /**
   * Concede um novo token de acesso conforme o token de refresh informado.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `refresh()` instead.
   *
   * This method doesn't expect any request body.
   */
  refresh$Response(params: Refresh$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CredencialDto>>> {
    return refresh(this.http, this.rootUrl, params, context);
  }

  /**
   * Concede um novo token de acesso conforme o token de refresh informado.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `refresh$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  refresh(params: Refresh$Params, context?: HttpContext): Observable<Array<CredencialDto>> {
    return this.refresh$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<CredencialDto>>): Array<CredencialDto> => r.body)
    );
  }

  /** Path part for operation `getInfoByTokenValidacao()` */
  static readonly GetInfoByTokenValidacaoPath = '/api/v1/auth/password/request/info';

  /**
   * Valida o token de alteração de senha.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getInfoByTokenValidacao()` instead.
   *
   * This method doesn't expect any request body.
   */
  getInfoByTokenValidacao$Response(params?: GetInfoByTokenValidacao$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<boolean>>> {
    return getInfoByTokenValidacao(this.http, this.rootUrl, params, context);
  }

  /**
   * Valida o token de alteração de senha.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getInfoByTokenValidacao$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getInfoByTokenValidacao(params?: GetInfoByTokenValidacao$Params, context?: HttpContext): Observable<Array<boolean>> {
    return this.getInfoByTokenValidacao$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<boolean>>): Array<boolean> => r.body)
    );
  }

  /** Path part for operation `getInfoByToken()` */
  static readonly GetInfoByTokenPath = '/api/v1/auth/info';

  /**
   * Recupera as informações do Usuário conforme o token informado.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getInfoByToken()` instead.
   *
   * This method doesn't expect any request body.
   */
  getInfoByToken$Response(params: GetInfoByToken$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CredencialDto>>> {
    return getInfoByToken(this.http, this.rootUrl, params, context);
  }

  /**
   * Recupera as informações do Usuário conforme o token informado.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getInfoByToken$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getInfoByToken(params: GetInfoByToken$Params, context?: HttpContext): Observable<Array<CredencialDto>> {
    return this.getInfoByToken$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<CredencialDto>>): Array<CredencialDto> => r.body)
    );
  }

}
