/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { create } from '../fn/income-controller/create';
import { Create$Params } from '../fn/income-controller/create';
import { getById } from '../fn/income-controller/get-by-id';
import { GetById$Params } from '../fn/income-controller/get-by-id';
import { IncomeDto } from '../models/income-dto';
import { IncomeListDto } from '../models/income-list-dto';
import { listAll } from '../fn/income-controller/list-all';
import { ListAll$Params } from '../fn/income-controller/list-all';
import { remove } from '../fn/income-controller/remove';
import { Remove$Params } from '../fn/income-controller/remove';
import { update } from '../fn/income-controller/update';
import { Update$Params } from '../fn/income-controller/update';

@Injectable({ providedIn: 'root' })
export class IncomeControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getById()` */
  static readonly GetByIdPath = '/1.0/incomes/{id}';

  /**
   * End point para obter dados por id
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getById$Response(params: GetById$Params, context?: HttpContext): Observable<StrictHttpResponse<IncomeDto>> {
    return getById(this.http, this.rootUrl, params, context);
  }

  /**
   * End point para obter dados por id
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getById(params: GetById$Params, context?: HttpContext): Observable<IncomeDto> {
    return this.getById$Response(params, context).pipe(
      map((r: StrictHttpResponse<IncomeDto>): IncomeDto => r.body)
    );
  }

  /** Path part for operation `update()` */
  static readonly UpdatePath = '/1.0/incomes/{id}';

  /**
   * End point para atualização de dados
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `update()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  update$Response(params: Update$Params, context?: HttpContext): Observable<StrictHttpResponse<IncomeDto>> {
    return update(this.http, this.rootUrl, params, context);
  }

  /**
   * End point para atualização de dados
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `update$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  update(params: Update$Params, context?: HttpContext): Observable<IncomeDto> {
    return this.update$Response(params, context).pipe(
      map((r: StrictHttpResponse<IncomeDto>): IncomeDto => r.body)
    );
  }

  /** Path part for operation `remove()` */
  static readonly RemovePath = '/1.0/incomes/{id}';

  /**
   * End point para remover dados por id
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `remove()` instead.
   *
   * This method doesn't expect any request body.
   */
  remove$Response(params: Remove$Params, context?: HttpContext): Observable<StrictHttpResponse<IncomeDto>> {
    return remove(this.http, this.rootUrl, params, context);
  }

  /**
   * End point para remover dados por id
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `remove$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  remove(params: Remove$Params, context?: HttpContext): Observable<IncomeDto> {
    return this.remove$Response(params, context).pipe(
      map((r: StrictHttpResponse<IncomeDto>): IncomeDto => r.body)
    );
  }

  /** Path part for operation `listAll()` */
  static readonly ListAllPath = '/1.0/incomes';

  /**
   * lista todos os dados
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listAll()` instead.
   *
   * This method doesn't expect any request body.
   */
  listAll$Response(params?: ListAll$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<IncomeListDto>>> {
    return listAll(this.http, this.rootUrl, params, context);
  }

  /**
   * lista todos os dados
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listAll$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listAll(params?: ListAll$Params, context?: HttpContext): Observable<Array<IncomeListDto>> {
    return this.listAll$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<IncomeListDto>>): Array<IncomeListDto> => r.body)
    );
  }

  /** Path part for operation `create()` */
  static readonly CreatePath = '/1.0/incomes';

  /**
   * End point para inclusão de dados
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `create()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  create$Response(params: Create$Params, context?: HttpContext): Observable<StrictHttpResponse<IncomeDto>> {
    return create(this.http, this.rootUrl, params, context);
  }

  /**
   * End point para inclusão de dados
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `create$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  create(params: Create$Params, context?: HttpContext): Observable<IncomeDto> {
    return this.create$Response(params, context).pipe(
      map((r: StrictHttpResponse<IncomeDto>): IncomeDto => r.body)
    );
  }

}
