/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { create } from '../fn/notification-preference-controller/create';
import { Create$Params } from '../fn/notification-preference-controller/create';
import { deleteItems } from '../fn/notification-preference-controller/delete-items';
import { DeleteItems$Params } from '../fn/notification-preference-controller/delete-items';
import { getById } from '../fn/notification-preference-controller/get-by-id';
import { GetById$Params } from '../fn/notification-preference-controller/get-by-id';
import { listAll } from '../fn/notification-preference-controller/list-all';
import { ListAll$Params } from '../fn/notification-preference-controller/list-all';
import { NotificationPreferenceDto } from '../models/notification-preference-dto';
import { remove } from '../fn/notification-preference-controller/remove';
import { Remove$Params } from '../fn/notification-preference-controller/remove';
import { update } from '../fn/notification-preference-controller/update';
import { Update$Params } from '../fn/notification-preference-controller/update';

@Injectable({ providedIn: 'root' })
export class NotificationPreferenceControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getById()` */
  static readonly GetByIdPath = '/1.0/notification-preferences/{id}';

  /**
   * Obter os dados completos de uma entidiade pelo id informado!
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getById$Response(params: GetById$Params, context?: HttpContext): Observable<StrictHttpResponse<NotificationPreferenceDto>> {
    return getById(this.http, this.rootUrl, params, context);
  }

  /**
   * Obter os dados completos de uma entidiade pelo id informado!
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getById(params: GetById$Params, context?: HttpContext): Observable<NotificationPreferenceDto> {
    return this.getById$Response(params, context).pipe(
      map((r: StrictHttpResponse<NotificationPreferenceDto>): NotificationPreferenceDto => r.body)
    );
  }

  /** Path part for operation `update()` */
  static readonly UpdatePath = '/1.0/notification-preferences/{id}';

  /**
   * Método utilizado para altlerar os dados de uma entidiade
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `update()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  update$Response(params: Update$Params, context?: HttpContext): Observable<StrictHttpResponse<NotificationPreferenceDto>> {
    return update(this.http, this.rootUrl, params, context);
  }

  /**
   * Método utilizado para altlerar os dados de uma entidiade
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `update$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  update(params: Update$Params, context?: HttpContext): Observable<NotificationPreferenceDto> {
    return this.update$Response(params, context).pipe(
      map((r: StrictHttpResponse<NotificationPreferenceDto>): NotificationPreferenceDto => r.body)
    );
  }

  /** Path part for operation `remove()` */
  static readonly RemovePath = '/1.0/notification-preferences/{id}';

  /**
   * Método utilizado para remover uma entidiade pela id informado
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `remove()` instead.
   *
   * This method doesn't expect any request body.
   */
  remove$Response(params: Remove$Params, context?: HttpContext): Observable<StrictHttpResponse<NotificationPreferenceDto>> {
    return remove(this.http, this.rootUrl, params, context);
  }

  /**
   * Método utilizado para remover uma entidiade pela id informado
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `remove$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  remove(params: Remove$Params, context?: HttpContext): Observable<NotificationPreferenceDto> {
    return this.remove$Response(params, context).pipe(
      map((r: StrictHttpResponse<NotificationPreferenceDto>): NotificationPreferenceDto => r.body)
    );
  }

  /** Path part for operation `listAll()` */
  static readonly ListAllPath = '/1.0/notification-preferences';

  /**
   * lista todos modelos
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listAll()` instead.
   *
   * This method doesn't expect any request body.
   */
  listAll$Response(params?: ListAll$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<NotificationPreferenceDto>>> {
    return listAll(this.http, this.rootUrl, params, context);
  }

  /**
   * lista todos modelos
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listAll$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listAll(params?: ListAll$Params, context?: HttpContext): Observable<Array<NotificationPreferenceDto>> {
    return this.listAll$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<NotificationPreferenceDto>>): Array<NotificationPreferenceDto> => r.body)
    );
  }

  /** Path part for operation `create()` */
  static readonly CreatePath = '/1.0/notification-preferences';

  /**
   * Método utilizado para realizar a inclusão de um entidade
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `create()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  create$Response(params: Create$Params, context?: HttpContext): Observable<StrictHttpResponse<NotificationPreferenceDto>> {
    return create(this.http, this.rootUrl, params, context);
  }

  /**
   * Método utilizado para realizar a inclusão de um entidade
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `create$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  create(params: Create$Params, context?: HttpContext): Observable<NotificationPreferenceDto> {
    return this.create$Response(params, context).pipe(
      map((r: StrictHttpResponse<NotificationPreferenceDto>): NotificationPreferenceDto => r.body)
    );
  }

  /** Path part for operation `deleteItems()` */
  static readonly DeleteItemsPath = '/1.0/notification-preferences/';

  /**
   * Método utilizado para remover varias entidades pelos ids informados
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteItems()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  deleteItems$Response(params: DeleteItems$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<NotificationPreferenceDto>>> {
    return deleteItems(this.http, this.rootUrl, params, context);
  }

  /**
   * Método utilizado para remover varias entidades pelos ids informados
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteItems$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  deleteItems(params: DeleteItems$Params, context?: HttpContext): Observable<Array<NotificationPreferenceDto>> {
    return this.deleteItems$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<NotificationPreferenceDto>>): Array<NotificationPreferenceDto> => r.body)
    );
  }

}
