/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createNotification } from '../fn/notification-controller/create-notification';
import { CreateNotification$Params } from '../fn/notification-controller/create-notification';
import { getUnreadNotifications } from '../fn/notification-controller/get-unread-notifications';
import { GetUnreadNotifications$Params } from '../fn/notification-controller/get-unread-notifications';
import { markAsRead } from '../fn/notification-controller/mark-as-read';
import { MarkAsRead$Params } from '../fn/notification-controller/mark-as-read';
import { NotificationDto } from '../models/notification-dto';
import { sendTipAsNotification } from '../fn/notification-controller/send-tip-as-notification';
import { SendTipAsNotification$Params } from '../fn/notification-controller/send-tip-as-notification';

@Injectable({ providedIn: 'root' })
export class NotificationControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `createNotification()` */
  static readonly CreateNotificationPath = '/1.0/notifications';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createNotification()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createNotification$Response(params: CreateNotification$Params, context?: HttpContext): Observable<StrictHttpResponse<NotificationDto>> {
    return createNotification(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createNotification$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createNotification(params: CreateNotification$Params, context?: HttpContext): Observable<NotificationDto> {
    return this.createNotification$Response(params, context).pipe(
      map((r: StrictHttpResponse<NotificationDto>): NotificationDto => r.body)
    );
  }

  /** Path part for operation `sendTipAsNotification()` */
  static readonly SendTipAsNotificationPath = '/1.0/notifications/send-tip';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `sendTipAsNotification()` instead.
   *
   * This method doesn't expect any request body.
   */
  sendTipAsNotification$Response(params: SendTipAsNotification$Params, context?: HttpContext): Observable<StrictHttpResponse<NotificationDto>> {
    return sendTipAsNotification(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `sendTipAsNotification$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  sendTipAsNotification(params: SendTipAsNotification$Params, context?: HttpContext): Observable<NotificationDto> {
    return this.sendTipAsNotification$Response(params, context).pipe(
      map((r: StrictHttpResponse<NotificationDto>): NotificationDto => r.body)
    );
  }

  /** Path part for operation `markAsRead()` */
  static readonly MarkAsReadPath = '/1.0/notifications/{id}/read';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `markAsRead()` instead.
   *
   * This method doesn't expect any request body.
   */
  markAsRead$Response(params: MarkAsRead$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return markAsRead(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `markAsRead$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  markAsRead(params: MarkAsRead$Params, context?: HttpContext): Observable<void> {
    return this.markAsRead$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getUnreadNotifications()` */
  static readonly GetUnreadNotificationsPath = '/1.0/notifications/unread';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getUnreadNotifications()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUnreadNotifications$Response(params: GetUnreadNotifications$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<NotificationDto>>> {
    return getUnreadNotifications(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getUnreadNotifications$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUnreadNotifications(params: GetUnreadNotifications$Params, context?: HttpContext): Observable<Array<NotificationDto>> {
    return this.getUnreadNotifications$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<NotificationDto>>): Array<NotificationDto> => r.body)
    );
  }

}
