/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { testModelReflection } from '../fn/test-controller/test-model-reflection';
import { TestModelReflection$Params } from '../fn/test-controller/test-model-reflection';

@Injectable({ providedIn: 'root' })
export class TestControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `testModelReflection()` */
  static readonly TestModelReflectionPath = '/1.0/test/';

  /**
   * End point to test
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `testModelReflection()` instead.
   *
   * This method doesn't expect any request body.
   */
  testModelReflection$Response(params?: TestModelReflection$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return testModelReflection(this.http, this.rootUrl, params, context);
  }

  /**
   * End point to test
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `testModelReflection$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  testModelReflection(params?: TestModelReflection$Params, context?: HttpContext): Observable<string> {
    return this.testModelReflection$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

}
