/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { getRandomTipByType } from '../fn/tip-controller/get-random-tip-by-type';
import { GetRandomTipByType$Params } from '../fn/tip-controller/get-random-tip-by-type';
import { TipDto } from '../models/tip-dto';

@Injectable({ providedIn: 'root' })
export class TipControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getRandomTipByType()` */
  static readonly GetRandomTipByTypePath = '/1.0/tips/{type}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getRandomTipByType()` instead.
   *
   * This method doesn't expect any request body.
   */
  getRandomTipByType$Response(params: GetRandomTipByType$Params, context?: HttpContext): Observable<StrictHttpResponse<TipDto>> {
    return getRandomTipByType(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getRandomTipByType$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getRandomTipByType(params: GetRandomTipByType$Params, context?: HttpContext): Observable<TipDto> {
    return this.getRandomTipByType$Response(params, context).pipe(
      map((r: StrictHttpResponse<TipDto>): TipDto => r.body)
    );
  }

}
