/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { create } from '../fn/user-controller/create';
import { Create$Params } from '../fn/user-controller/create';
import { CredencialDto } from '../models/credencial-dto';
import { update } from '../fn/user-controller/update';
import { Update$Params } from '../fn/user-controller/update';

@Injectable({ providedIn: 'root' })
export class UserControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `create()` */
  static readonly CreatePath = '/v1/user/novo';

  /**
   * Permite a criação de um novo usuário
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `create()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  create$Response(params: Create$Params, context?: HttpContext): Observable<StrictHttpResponse<CredencialDto>> {
    return create(this.http, this.rootUrl, params, context);
  }

  /**
   * Permite a criação de um novo usuário
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `create$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  create(params: Create$Params, context?: HttpContext): Observable<CredencialDto> {
    return this.create$Response(params, context).pipe(
      map((r: StrictHttpResponse<CredencialDto>): CredencialDto => r.body)
    );
  }

  /** Path part for operation `update()` */
  static readonly UpdatePath = '/v1/user/atualizar';

  /**
   * Permite a atualização de um usuário
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `update()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  update$Response(params: Update$Params, context?: HttpContext): Observable<StrictHttpResponse<CredencialDto>> {
    return update(this.http, this.rootUrl, params, context);
  }

  /**
   * Permite a atualização de um usuário
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `update$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  update(params: Update$Params, context?: HttpContext): Observable<CredencialDto> {
    return this.update$Response(params, context).pipe(
      map((r: StrictHttpResponse<CredencialDto>): CredencialDto => r.body)
    );
  }

}
